# Generated by Django 3.2.5 on 2021-07-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=15)),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
    ]
